---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[test]
      - recipe[chef-server-ingredient]
    attributes:
  - name: override_package_versions
    run_list:
      - recipe[test]
      - recipe[chef-server-ingredient]
    attributes:
      test:
        chef-server-core:
          version: 12.0.0-rc.5-1
